### PR TITLE
Updates Element.atomic_mass field based on IUPAC 2021 tabulation

### PR DESCRIPTION
**Pull request by NicholasWMRitchie**
The IUPAC tabulation is the canonical source for this data.  The typos related to incorrect interpretation of uncertainties have also been addressed.

### CODE REVIEW

**Comment by NicholasWMRitchie** [comment]
Addresses issues #43 and #56.

**Comment by carstenbauer** [comment]
Thanks! Should we perhaps keep the sentence "Some information has been (and will be) added over time."? I'm not sure if there is already information in the package that doesn't come from either one of the sources you mentioned.

**Comment by NicholasWMRitchie** [comment]
This sentence is symptomatic of the ambiguous provenance and update mechanisms associated with the data in PeriodicTable.jl.  I find this ambiguity hinders the use of this package for serious scientific work.  PT.jl should be able to reference the primary source of all data (publication reference preferably) . It is an important part of the reproducibility and traceability of scientific results.  When the data changes, the semantic version number should be updated to reflect this is, from the perspective of a scientific user, a breaking change that I'd need to evaluate to decide whether I want to accept this change.

Currently, PeriodicTable.jl "sort of" addresses this question by referencing Wikipedia.  However, this only passes the problem along.  For one, since websites change, you need to reference the date the data was downloaded.  Second, it makes tracing the provenance of a collection of values tedious and makes updating them difficult.  PT.jl shouldn't be using Wikipedia.  It should go directly to reference-able primary sources.

I'm going to open a separate issue to highlight this problem.

**Comment by NicholasWMRitchie** [comment]
This pull-request is ready to go and fixes a significant bug.  Can it be merged?

**Comment by carstenbauer** [comment]
Sorry, forgot about it. I'll tag a new release

**Pull request merged**
