### PR TITLE
Julia 1.0 support: new iterator interface

### PR DESCRIPTION
**Pull request by carstenbauer**
This PR adds support for the new iterator interface to make the package work in Julia 1.0.

### CODE REVIEW

**Comment by carstenbauer** [comment]
I suggest tagging a new release after this has been merged to make the package function in 1.0.

**Comment by rahulkp220** [comment]
Thanks for the PR @crstnbr , Can you also update the `REQUIRE` file too?

**Comment by carstenbauer** [comment]
What update do you have in mind?

Currently it contains `julia 0.6` which should include all Julia versions >= 0.6, which seems fine to me (Note that I didn't remove the old iterator interface implementation).

**Comment by rahulkp220** [comment]
I was thinking to upgrade it to Julia 0.7, which would then take it to the next stage easily with 1.0. I guess the tests were already fixed for deprecations in an earlier PR

**Comment by carstenbauer** [comment]
So you want to drop 0.6 support? If so, I should delete the old iterator interface (and version based branch), which is only needed for julia < 0.7.

**Comment by rahulkp220** [comment]
Hmm, let's leave it there. I wished to go post 0.7, but I guess, its okay for some time to have 0.6 supported. I agree with your initial comment on keeping it at 0.6. 

Also, I have sent an invite for you to become a collaborator :)

**Comment by carstenbauer** [comment]
Ok, thanks! I'll finish this up (will add some iterator test).

**Comment by carstenbauer** [comment]
v1.0 CI failures are due to `Pkg not defined`. This will be a reason to drop 0.6 at some point. I'll rebase and merge.

**Comment by rahulkp220** [comment]
Yeah, I guess a move to 0.7 will be inevitable very soon.

**Comment by carstenbauer** [comment]
Could you tag a new release such that 1.0 users will be able to use the package?

**Comment by rahulkp220** [comment]
For any new release, just draft a new one and `attobot` will take care of the rest :)
Anyways, you can track it here https://github.com/JuliaLang/METADATA.jl/pull/17855

**Pull request merged**
